package enumeraciones;

public enum Ciudad {
	LETICIA, MEDELLÍN, ARAUCA, BARRANQUILLA, CARTAGENADEINDIAS, TUNJA, MANIZALES, FLORENCIA, YOPAL, POPAYÁN, VALLEDUPAR,
	QUIBDÓ, MONTERÍA, BOGOTÁ, INÍRIDA, SANJOSÉDELGUAVIARE, NEIVA, RIOHACHA, SANTAMARTA, VILLAVICENCIO, PASTO,
	SANJOSÉDECÚCUTA, MOCOA, ARMENIA, PEREIRA, SANANDRÉS, BUCARAMANGA, SINCELEJO, IBAGUÉ, CALI, MITÚ, PUERTOCARREÑO
}
