package enumeraciones;

public enum Departamento {
	AMAZONAS, ANTIOQUIA, ARAUCA, ATLÁNTICO, BOLIVAR, BOYACÁ, CALDAS, CAQUETÁ, CASANARE, CAUCA, CESAR, CHOCÓ, CÓRDOBA,
	CUNDINAMARCA, GUAINÍA, GUAJIRA, GUAVIARE, HUILA, MAGDALENA, META, NARIÑO, NORTEDESANTANDER, PUTUMAYO, QUINDÍO,
	RISARALDA, SANANDRÉSYPROVIDENCIA, SANTANDER, SUCRE, TOLIMA, VALLEDELCAUCA, VAUPÉS, VICHADA
}
